# Generated by Django 5.2.6 on 2025-09-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15, verbose_name='Codigo')),
                ('procedimiento', models.CharField(max_length=100, verbose_name='Procedimiento')),
                ('precio', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
            },
        ),
        migrations.AlterModelOptions(
            name='administracion',
            options={'verbose_name': 'Administracion', 'verbose_name_plural': 'Administracion'},
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('procedimiento', models.CharField(max_length=100, verbose_name='Prestacion')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.profesionalsalud', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Agenda',
                'verbose_name_plural': 'Agendas',
            },
        ),
        migrations.AddField(
            model_name='profesionalsalud',
            name='procedimiento',
            field=models.ManyToManyField(to='administracion.procedimiento', verbose_name='Procedimiento'),
        ),
    ]
