# Generated by Django 5.2.6 on 2025-09-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
            },
        ),
        migrations.RemoveField(
            model_name='recepcionista',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='personalsalud',
            options={'verbose_name': 'Personal de Salud', 'verbose_name_plural': 'Personal de Salud'},
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='procedimiento',
        ),
        migrations.RemoveField(
            model_name='personalsalud',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='personalsalud',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='personalsalud',
            name='user',
        ),
        migrations.AlterField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='especialidad',
            field=models.CharField(default='Sin Especialidad', max_length=100, verbose_name='Especialidad'),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='nombre',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='personalsalud',
            name='rut',
            field=models.CharField(max_length=255, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='codigo',
            field=models.CharField(max_length=100, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='personal_salud',
            field=models.ManyToManyField(blank=True, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='precio',
            field=models.IntegerField(default=0, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='procedimiento',
            name='procedimiento',
            field=models.CharField(max_length=255, verbose_name='Procedimiento'),
        ),
        migrations.DeleteModel(
            name='Administracion',
        ),
        migrations.DeleteModel(
            name='Recepcionista',
        ),
    ]
