# Generated by Django 5.2.6 on 2025-09-30 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalsalud',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='personal_salud',
            field=models.ManyToManyField(blank=True, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='secretaria',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicio',
            name='administracion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.administrador', verbose_name='Administración'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='personal',
            field=models.ManyToManyField(blank=True, null=True, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='recepcion',
            field=models.ManyToManyField(blank=True, null=True, to='administracion.secretaria', verbose_name='Recepcion'),
        ),
    ]
