# Generated by Django 5.2.6 on 2025-10-06 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='personalsalud',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='personal_salud',
            field=models.ManyToManyField(to='administracion.personalsalud', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='personal',
            field=models.ManyToManyField(to='administracion.personalsalud', verbose_name='Profesional'),
        ),
    ]
