# Generated by Django 5.2.6 on 2025-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_procedimiento_alter_administracion_options_agenda_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesionalsalud',
            name='procedimiento',
        ),
        migrations.AddField(
            model_name='procedimiento',
            name='profesional_salud',
            field=models.ManyToManyField(to='administracion.profesionalsalud', verbose_name='Procedimiento'),
        ),
    ]
