# Generated by Django 5.2.6 on 2025-09-25 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_servicio_remove_recepcionista_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
    ]
