# Generated by Django 5.2.6 on 2025-09-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_servicio_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='profesional',
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ManyToManyField(blank=True, null=True, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
    ]
