# Generated by Django 5.2.6 on 2025-09-26 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_remove_agenda_profesional_agenda_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='personal',
        ),
        migrations.AddField(
            model_name='servicio',
            name='personal',
            field=models.ManyToManyField(blank=True, null=True, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
    ]
