# Generated by Django 5.2.6 on 2025-09-26 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_remove_servicio_personal_servicio_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='profesional',
        ),
        migrations.AddField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.procedimiento', verbose_name='Profesional'),
        ),
    ]
