# Generated by Django 5.2.6 on 2025-09-26 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_remove_agenda_profesional_agenda_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.personalsalud', verbose_name='Profesional'),
        ),
    ]
