# Generated by Django 5.2.6 on 2025-10-09 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_nombre_remove_user_password1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mfa_enabled',
            new_name='mfa_verified',
        ),
    ]
