# Generated by Django 5.2.6 on 2025-10-09 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0001_initial'),
        ('recepcion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Sin Convenio', max_length=100, verbose_name='Nombre del Convenio')),
                ('descuento', models.IntegerField(default=0, verbose_name='Descuento')),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_compra', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Compra')),
                ('fecha', models.DateField(verbose_name='Fecha del Pago')),
                ('monto', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Monto del Pago')),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pago')),
                ('is_pagado', models.BooleanField(default=False, verbose_name='¿Está Pagado?')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinpro.convenio', verbose_name='Convenio')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='ReservaHora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(verbose_name='Fecha de la Reserva')),
                ('hora_reserva', models.TimeField(verbose_name='Hora de Inicio')),
                ('is_confirmada', models.BooleanField(default=False, verbose_name='¿Está Confirmada?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('noregistrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recepcion.noregistrado', verbose_name='No Registrado')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinpro.pago', verbose_name='Pago')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.personalsalud', verbose_name='Profesional')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Reserva de Hora',
                'verbose_name_plural': 'Reservas de Horas',
            },
        ),
    ]
