# Generated by Django 5.2.6 on 2025-09-25 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinpro', '0002_remove_convenio_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.AddField(
            model_name='pago',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinpro.convenio', verbose_name='Convenio'),
        ),
    ]
