# Generated by Django 5.2.6 on 2025-09-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinpro', '0003_remove_user_rol_pago_convenio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservahora',
            old_name='fecha',
            new_name='fecha_reserva',
        ),
        migrations.RenameField(
            model_name='reservahora',
            old_name='hora_inicio',
            new_name='hora_reserva',
        ),
        migrations.RenameField(
            model_name='reservahora',
            old_name='paciente_id',
            new_name='paciente',
        ),
        migrations.RenameField(
            model_name='reservahora',
            old_name='pago_id',
            new_name='pago',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='reservahora',
            name='hora_fin',
        ),
        migrations.AddField(
            model_name='reservahora',
            name='is_asistencia',
            field=models.BooleanField(default=False, verbose_name='¿Asistió?'),
        ),
        migrations.AddField(
            model_name='reservahora',
            name='is_cancelada',
            field=models.BooleanField(default=False, verbose_name='¿Está Cancelada?'),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
    ]
