# Generated by Django 5.2.6 on 2025-10-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoRegistrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, default='No Presenta', max_length=15, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='No Presenta', max_length=254, null=True, unique=True, verbose_name='Correo Electrónico')),
                ('rol', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'No Registrado',
                'verbose_name_plural': 'No Registrados',
            },
        ),
    ]
